# Generated by Django 6.0.1 on 2026-01-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='u_name',
        ),
    ]
