# Generated by Django 6.0.1 on 2026-01-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_rename_name_student_u_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
