# Generated by Django 6.0.1 on 2026-01-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_student_blood_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
