# Generated by Django 6.0.1 on 2026-02-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=True, max_length=100),
        ),
    ]
