# Generated by Django 6.0.1 on 2026-02-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='v_status',
            field=models.IntegerField(default=0),
        ),
    ]
